# Generated by Django 3.0.3 on 2020-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='姓名', max_length=20)),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女')], help_text='性别', max_length=1)),
                ('id_card', models.CharField(help_text='身份证号', max_length=100)),
                ('live_room', models.CharField(help_text='入住房间', max_length=10)),
                ('deposit', models.CharField(help_text='押金,单位元', max_length=10)),
                ('live_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
