# Generated by Django 3.0.3 on 2020-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_out',
            name='deposit',
            field=models.CharField(help_text='押金是否退还', max_length=50),
        ),
    ]
