# Generated by Django 3.0.3 on 2020-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommsg', '0003_roommsg_peo_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommsg',
            name='house_tel',
            field=models.CharField(default=101, help_text='客房电话', max_length=10),
        ),
    ]
