# Generated by Django 3.0.3 on 2020-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommsg', '0005_check_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check_out',
        ),
    ]
