# Generated by Django 3.0.3 on 2020-05-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommsg', '0006_delete_check_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_password',
        ),
    ]
