# Generated by Django 3.0.3 on 2020-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_password',
            name='email',
            field=models.CharField(default='xxyy@xx.com', help_text='邮箱', max_length=200),
        ),
    ]
