# Generated by Django 3.0.3 on 2020-05-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_password',
            table='user',
        ),
    ]
